### ISSUE TITLE
Add routes links

### ISSUE THREAD

**Issue by julianzdelat** [julianzdelat/blockchain_frontend#9]
1) Home (Orders-transactions)
2) Admin (CRUD users [admin, employee]) 
3) Items (CRUD)
4) Payments (CRUD)

**Comment by andreschabba** [comment]
@julianzdelat @chriznm about this issue:
I have already started with this configuration on issue #6, but I will not close it because I think it will be necessary to add more routes to our app. Anyway, I will assignee it to myself and retake it later.
